version: '3.8'

services:
  fastapi:
    build: .
    container_name: speechkit-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
